name: Example Books Backend Build

on:
  push:
    branches:
      - "main"
    paths:
      - "./example-books-backend"
      - ".github/workflows/example-books-backend-build.yaml"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: "./example-books-backend"
          push: true
          tags: ghcr.io/maxmanthey/${{ github.event.repository.name }}/example-books-backend:${{ github.sha }},ghcr.io/maxmanthey/${{ github.event.repository.name }}/example-books-backend:latest
