name: Example Books DB Build

on:
  push:
    branches:
      - "main"
    paths:
      - "example-books-db"
      - ".github/workflows/example-books-db-build.yaml"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      # - name: Extract metadata for Docker
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:example-books-db"
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/example-books-db:${{ github.sha }},ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/example-books-db:latest
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
